baseURL = 'https://felipe.nubecita.eu/'
languageCode = 'en-gb'
title = 'My personal website'
theme = 're-terminal'
pagination.pagerSize = 5

[params]
  contentTypeName = 'posts'
  showMenuItems = 4
  themeColor = "orange"
  centerTheme = true
  framed = true
  showFullContent = false
  showHeaderIcons = true
  showFooterIcons = true
  enableRobotsTXT = true

  [[params.footer.socialIcons]]
    name = "email"
    title = 'Send me an email'
    url = "mailto:admin@nubecita.eu"
  [[params.footer.socialIcons]]
    name = "github"
    title = 'My Github page'
    url = "https://github.com/felipet"
  [[params.footer.socialIcons]]
    name = "linkedin"
    title = 'Linkedin profile'
    url = "https://www.linkedin.com/in/felipe-torres-gonzález"
  [[params.footer.socialIcons]]
    name = "instagram"
    title = 'My Instagram page'
    url = "https://instagram.com/feltorgrafo"
  [[params.footer.socialIcons]]
    name = "x"
    title = 'My X profile'
    url = "https://x.com/felipteg"

  [[params.header.socialIcons]]
    name = "github"
    title = 'My Github page'
    url = "https://github.com/felipet"
  [[params.header.socialIcons]]
    name = "linkedin"
    title = 'Linkedin profile'
    url = "https://www.linkedin.com/in/felipe-torres-gonzález"

[markup.goldmark.renderer]
  unsafe = true

[languages]
  [languages.en.params]
    languageName = "English"
    title = "Felipe's site"
    subtitle = "My personal website"
    owner = "Felipe Torres González"
    keywords = "blog, developer"
    copyright = "© 2025 - Felipe Torres González"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Felipe's site"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "My Projects"
        url = "/projects"
      [[languages.en.menu.main]]
         identifier = "other"
         name = "Other"
      [[languages.en.menu.main]]
         parent = "other"
         identifier = "tags"
         name = "Tags"
         url = "/tags"
      [[languages.en.menu.main]]
         parent = "other"
         identifier = "categories"
         name = "Categories"
         url = "/categories"

